### ISSUE TITLE
reset alert status

### ISSUE THREAD

**Issue by piwi3910** [ilovepancakes95/idrac_snmp-grafana#10]
I had a disk failure and the status went red.
Even after replacing the disk and in idrac all looks good again, the status of the disk remains red in your panel.
Any idea how to reset it, and why it's not reading the new status.

**Comment by ilovepancakes95** [comment]
Which status went red? Global or storage? And which iDrac version and system are you using?

**Comment by piwi3910** [comment]
Dell Customer Communication - Confidential

Global and PSU and Storage

I unplugged a psu -> idrac goes in error -> Grafana goes Red
Replug -> idrac back to ok -> I even reset the log -> Grafana stays red

Did the same for a disk
Dell R720XD with 2.52..52.52

**Comment by ilovepancakes95** [comment]
If you run `snmpget -v 1 -c public [idrac IP here] .1.3.6.1.4.1.674.10892.5.2.1.0` from the command line on the machine running telegraf what do you get as the result? Use the iDRAC IP for the unit that is supposedly reporting the wrong status. That OID number is for "Global Status" on my R720xd running same iDRAC version.
