### ISSUE TITLE
No data for System overview, PSU Status, RAID Battery, System Watts, Fan speed in iDrac8

### ISSUE THREAD

**Issue by sixxar** [ilovepancakes95/idrac_snmp-grafana#11]
Can't get data for system overview, PSU Status, RAID Battery, system watts, Fan speed. Also don't get all iDracs (have 2 with ESXi and one with Oracle Linus), only get info from one ESXi and Oracle Linux.

**Comment by ilovepancakes95** [comment]
What does `snmpget -v 1 -c public [idrac IP here] .1.3.6.1.4.1.674.10892.5.2.1.0` return when run from same machine hosting telegraf?
