### ISSUE TITLE
Struggling to get this to work on Dell servers

### ISSUE THREAD

**Issue by G0nz0uk** [ilovepancakes95/idrac_snmp-grafana#12]
Hello,

I was wondering if I need to download any mibs to get this to work?  We use Idrac 8 and 9s with snmp v1.

I'm already using Grafana, Telegraf and InfluxDB to monitor other systems, but can't get this to work.

I created a new dracs.conf and added this and restarted grafana and telegraf and I don't see much.

I put your config in from https://grafana.com/grafana/dashboards/12106
and just added 1 server:

[[inputs.snmp]]
  agents = [ "https://10.119.1.111:161" ]
  version = 1
  community = "public"
  name = "idrac-hosts"

What could I be doing wrong?

Thanks

**Comment by coolguy1771** [comment]
take https:// out

**Comment by ilovepancakes95** [comment]
Can you try without the https? Only IP address and port should be in there. And it definitely is not HTTPS access anyway, it's snmp over port 161.

**Comment by G0nz0uk** [comment]
Perfect silly me, all working, I saw url and thought I needed to use that.  Love your dashboard!!

**Comment by G0nz0uk** [comment]
One last thing, 2 drac cards I imported had the wrong name, so I've gone into the Drac cards and updated this info and they have come in as fresh devices but look good, however the old names are still there and it I delete them from the dashboard they come back, any ideas how to predominately remove them?

**Comment by ilovepancakes95** [comment]
I see gaps on mine if I make the time interval for that dashboard something short like 5 minutes or 10 minutes. The longer the period, the gaps aren't noticeable since they get so small. But, if you prefer to use shorter time periods like that for your dashboard I believe the gap spacing or size of bars essentially can be customized in the panels settings.

**Comment by Tooxic** [comment]
Does any one know how to solve this issue? 

`Error in plugin: agent 10.0.10.25:161: gathering table idrac-hosts: performing bulk walk for field bios-version: reconn                                                             ecting: SecurityParameters.UserName is required`

**Comment by coolguy1771** [comment]
Are you using SNMP v3?
