### ISSUE TITLE
Does any one know how to solve this issue?

### ISSUE THREAD

**Issue by ilovepancakes95** [ilovepancakes95/idrac_snmp-grafana#13]
Does any one know how to solve this issue? 

`Error in plugin: agent 10.0.10.25:161: gathering table idrac-hosts: performing bulk walk for field bios-version: reconn                                                             ecting: SecurityParameters.UserName is required`

_Originally posted by @Tooxic in https://github.com/ilovepancakes95/idrac_snmp-grafana/issues/12#issuecomment-762285156_

**Comment by ilovepancakes95** [comment]
> Does any one know how to solve this issue?
> 
> `Error in plugin: agent 10.0.10.25:161: gathering table idrac-hosts: performing bulk walk for field bios-version: reconn ecting: SecurityParameters.UserName is required`
> 
> _Originally posted by @Tooxic in [#12 (comment)](https://github.com/ilovepancakes95/idrac_snmp-grafana/issues/12#issuecomment-762285156)_

What is the command you are trying to run or the software is trying to run that then produces this error?

**Comment by Tooxic** [comment]
> > Does any one know how to solve this issue?
> > `Error in plugin: agent 10.0.10.25:161: gathering table idrac-hosts: performing bulk walk for field bios-version: reconn ecting: SecurityParameters.UserName is required`
> > _Originally posted by @Tooxic in [#12 (comment)](https://github.com/ilovepancakes95/idrac_snmp-grafana/issues/12#issuecomment-762285156)_
> 
> What is the command you are trying to run or the software is trying to run that then produces this error?

![image](https://user-images.githubusercontent.com/33166817/104929447-2e3a1880-59a4-11eb-85c4-1464ebc2bcf3.png)

**Comment by juddgaddie** [comment]
Looks like that error is coming from the Golang SNMP library that telegraf is using. 
See: https://github.com/gosnmp/gosnmp/blob/098294287f6e861fc96553c535f95dfa49cdb09f/v3_usm.go#L325

My guess is the SNMP server you are connecting to is SNMPv3 (The config for this dashboard is for SNMPv1)

The SNMPv3 protocol requires at least a username for NoAuthPriv - see https://www.webnms.com/simulator/help/sim_network/netsim_conf_snmpv3.html

Best bet is just use SNMPv1 or configure a authentication for SNMPv3
