### ISSUE TITLE
Migrate from single stat panel to stat panel

### ISSUE THREAD

**Issue by juddgaddie** [ilovepancakes95/idrac_snmp-grafana#14]
Thank you so much for sharing such an awesome dashboard!

https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/

See screenshot

![image](https://user-images.githubusercontent.com/10848265/105923552-786e6a00-6034-11eb-9d6a-330c6c067ecf.png)

I'm also not sure if the stat panel could replace the global status panel ?

**Comment by ilovepancakes95** [comment]
I'll look into this when upgrading the dashboard to work with newer versions of Grafana. For now, the current panel still works fine in Grafana v7.1.5 which is what the dashboard was designed with/for. Definitely open to any push requests someone wants to implement for future proofing the dashboard in meantime.
