### ISSUE TITLE
Question: What do you do about alerts ?

### ISSUE THREAD

**Issue by juddgaddie** [ilovepancakes95/idrac_snmp-grafana#15]
Alerts only work with graph panels. Do you use alerts?

The only way I have at the moment is to create graph panels for alerts that I want.

Fortunately Alerting is getting an overhaul in Grafana 8 - see https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Falerting-ng+

I'm not sure if it will support Alerts on other panel types..

**Comment by ilovepancakes95** [comment]
I don't have alerts setup for that very reason, but yes that is the way I would do it to get alerts right now. Will be nice to have Grafana 8 with better alerts.
