### ISSUE TITLE
Temperature wrong on r7515.  Grafana is showing CPU temp as inlet temp.

### ISSUE THREAD

**Issue by haydonryan** [ilovepancakes95/idrac_snmp-grafana#22]
HI there,

This is a great dashboard -on my r7515 the temps section is messed up.
Three temps show in iDrac:
- CPU, Inlet Temp, and Exhaust Temp 

In Grafana:
- Inlet temp - is actually CPU temp.
- exhaust temp - is actually inlet temp
- CPU temp missing.

Could this be a SNMP MIBs issue?

**Comment by haydonryan** [comment]
Ok I swapped the entries for the the temps in the telegraf and it appears to have corrected the issue.

**Comment by ilovepancakes95** [comment]
Unfortunately, it seems that Dell's iDRAC behavior is VERY picky about the order of OIDs and I have seen OIDs swap what they link to based on the very specific combination of hardware/generation someone has. Seems like poor design on Dell's part so not sure what can be done to fix that.
