### ISSUE TITLE
Grafana dashboard not working

### ISSUE THREAD

**Issue by berkayhapcioglu** [ilovepancakes95/idrac_snmp-grafana#25]
Influxdb can read data from snmp but grafana dashboards are not working.

**Comment by Jimmy-SafeCash** [comment]
Same problem, data is in influxdb (configured to flux query), dashboard has no data.

**Comment by xTheDoctah** [comment]
Easiest solution host influx 1.8,3 and read data from that.

**Comment by SiskoUrso** [comment]
> Easiest solution host influx 1.8,3 and read data from that.

Had the same issue and came here looking for suggestions, this was the solution as it did not work with flux.
