### ISSUE TITLE
BIOS and Service Tag Question

### ISSUE THREAD

**Issue by sinankizar** [ilovepancakes95/idrac_snmp-grafana#29]
Hello and thank you for your work this is a lifesaver indeed.

Can't see the bios and service tags here:

![image](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/28201097/8642a37c-9c56-4138-88ba-6e772967c441)

But can see tag here and want to add a column to this:

![Screenshot 2023-06-08 at 17 54 18](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/28201097/336e4298-49ff-4ed0-ad04-2289d6437f5f)

How to add a column to this table which includes BIOS ınfo?

Thanks in advance.

**Comment by ilovepancakes95** [comment]
To add a column into that table click the System Overview heading and choose "edit" then scroll down and add a query. Define the new query to show the information you need and format it as a table and group it by system name. See below screenshot. That should do what you want.

<img width="969" alt="Screen Shot 2023-06-14 at 2 17 57 PM" src="https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/52054078/0de899d3-336e-4d64-b1c3-9cfd79e070e2">

**Comment by sinankizar** [comment]
Thanks for the tip but this adds a new row under already listed details:
![image](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/28201097/754cbf0f-a2f6-4191-ac8f-7d93ace9ec30)

**Comment by ilovepancakes95** [comment]
Perhaps! I haven't upgraded Grafana or changed out any panels in a while so would be curious. Although, despite that change, not sure why it would break current functionality if staying on the old.

**Comment by sinankizar** [comment]
This one would do the trick too byut I can't get any info in this panel either:
![image](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/28201097/933a0a6a-fb90-479f-ab00-70855d3fff40)

**Comment by Latezly** [comment]
![image](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/17759624/b0c362ba-b1a0-4bc8-9ae1-dffa6bdeafd5)
Value options→Fields

Change the original "Numeric Fields" to "idrac-hosts.system-servicetag" to display the content normally. The same principle can also be used to modify "bios-version".

But there is a new problem. I am not sure that if there are two servers in this panel, the information of the second idrac displayed will not have an edit button, and it will not be effective for the above.
