### ISSUE TITLE
iDrac 6 enterprise

### ISSUE THREAD

**Issue by jasazick** [ilovepancakes95/idrac_snmp-grafana#3]
Tested with an R210 II with iDrac 6 enterprise - doesn't seem to work. (Works like a champ on my R630 with iDrac 8 express)

**Comment by krystiancharubin** [comment]
Yeah this only works with RX20+ older ones don't return very little snmp data.

**Comment by ilovepancakes95** [comment]
I've heard from a few people now that yes, iDRAC 6 apparently provides way less data via SNMP than newer versions, unfortunately.
