### ISSUE TITLE
Angular Deprecated - Panels need to be updated

### ISSUE THREAD

**Issue by bgatestmg** [ilovepancakes95/idrac_snmp-grafana#35]
Panels need to be upgraded to stay compatible with Grafana 11, i issued a pull request to meet the new requirements

**Comment by ilovepancakes95** [comment]
Thanks for the contribution, will review and test over next couple of days. A good time to finally get my Grafana instance upgraded to latest version.

**Comment by bgatestmg** [comment]
happy to help! lots of nice new features! 
![Screenshot 2024-05-15 at 1 58 55 PM](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/153768976/bd34e283-d949-4249-b7c2-3a9508802f9f)
![Screenshot 2024-05-15 at 1 59 05 PM](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/153768976/09452741-0005-4175-8c60-a4f67c8ab780)

**Comment by bgatestmg** [comment]
![Screenshot 2024-05-15 at 1 59 48 PM](https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/153768976/df1bf302-1c68-42eb-aef0-84c374d940aa)
