### ISSUE TITLE
Partial information on T320

### ISSUE THREAD

**Issue by aqwserf** [ilovepancakes95/idrac_snmp-grafana#4]
Hi ! I already posted a review on Grafana but I saw that there's a github so....
I successfully installed your dashboard but I only have some partial information:

![Screenshot from 2020-05-08 16-40-57](https://user-images.githubusercontent.com/29235861/81417351-569e2180-914b-11ea-8bca-ff2efd343699.png)

Do you have any other information to provide or any workaround ? 
Thanks !

**Comment by ilovepancakes95** [comment]
Which idrac version, firmware, and system model are you trying this with?

**Comment by aqwserf** [comment]
Thanks for your quick answer.
My bad, there was a confusion between the databases, everything works fine expect the CPU Temp. I'm investigating to fix the OID to fit mine.
Anyway, thanks for your great dashboard !

**Comment by ilovepancakes95** [comment]
Glad you like it! Someone else had CPU temp display issue too and found out OIDs were completely different because they have single CPU system instead of dual CPU. Not sure if you are single or dual CPU though.
