### ISSUE TITLE
The dashboard show "no data to show" and "no data"

### ISSUE THREAD

**Issue by hzd2020** [ilovepancakes95/idrac_snmp-grafana#8]
I have Install and setup Telegraf, InfluxDB, and Grafana to work with eachother, and  InfluxDB have telegraf  collection data from idrac.but  the dashboard still don't show any data, show "no data" or "no data to show". 
![image](https://user-images.githubusercontent.com/65700504/82527878-1aff5080-9b6a-11ea-9990-1f4f611a9074.png)

in the above image $idrac_host  What does it mean？

**Comment by hzd2020** [comment]
show tag values from  "idrac-hosts" with key="system-name"  not have return any values. I using  influxdb 1.64
![image](https://user-images.githubusercontent.com/65700504/82532659-6ae31500-9b74-11ea-93f6-568bb1e24feb.png)

**Comment by mentalinc** [comment]
You need to change the variables in the scripts to your ip address of the
idrac

**Comment by hzd2020** [comment]
I reinstall influxdb from 1.64 to 1.8 . now "SHOW TAG VALUES ON "idrac2985" FROM "idrac-hosts" WITH KEY="system-name"" is right.
![image](https://user-images.githubusercontent.com/65700504/82533700-64ee3380-9b76-11ea-85d0-ca823b434f13.png)  may be influxdb 1.64 problem.

**Comment by ilovepancakes95** [comment]
And your other data also comes through now too? It seems the first error you had, was relating to the database not actually being in existence I think. Maybe it wasn't be auto-created correctly in the previous version.

**Comment by hzd2020** [comment]
Now Dashboard show data is normal as:
![image](https://user-images.githubusercontent.com/65700504/82533983-f2ca1e80-9b76-11ea-825f-92a6183bdefe.png)

**Comment by hzd2020** [comment]
[``](

- 

- [ ] 

> `**### 1. url**`

)
